config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos do
      member do
      post :item_done
    end
   end 
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :notes, :due_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController


  before_action :set_todo, :only => [:show, :edit, :update, :destroy, :item_done]

  def index
    @todos = Todo.all
  end  


  def new
    @todo = Todo.new
    @allow_modify = true
  end


  def create
    @todo = Todo.new(todo_params)
    @todo.done = false
    if @todo.save
      redirect_to todos_url  
    else
      @allow_modify = true
      render :new
    end

  end

  # ================== #
  def show
    @allow_modify = false
  end

  def edit
    @allow_modify = true
  end
  # ================== #

  def item_done
    @todo.update(done: !(@todo.done))
    
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todos_url
    else
      @allow_modify = true
      render :action => :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_url
  end


  # ================================== # 
  private
  def todo_params
    params.require(:todo).permit(:title, :notes, :due_date, :done)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ATodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">
  <%= form_for @todo, :html => {:class => "form-horizontal center"} do |f| %>
  <div class="form-group">
    <%= f.label :title, "項目", class: "col-md-2 control-label" %>
    <div class="col-md-7">
      <%= f.text_field :title, class: "form-control", readonly: onlyread  %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notes, "內容", class: "col-md-2 control-label" %>
    <div class="col-md-7">
      <%= f.text_area :notes, class: "form-control", readonly: onlyread, :rows => 6 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :due_date, "截止日", class: "col-md-2 control-label" %>
    <% if @allow_modify %>
      <div class="col-md-7">
        <%= f.date_select :due_date, class: "form-control" %>
      </div>
    <% else %>
      <div class="col-md-7">
        <%= f.text_field :due_date, class: "form-control", readonly: true  %>
      </div>
    <% end %>

  </div>


  <div class="form-group">
    <% if @allow_modify %>
      <div class="col-md-2">
      </div>
      <div class="col-md-3">
        <%= f.submit "送出", class: "btn btn-default btn-primary" %>
      </div>

      <div class="col-md-2">
      </div>
      <div class="col-md-2">
        <%= link_to "首頁", todos_url, class: "pull-right"%>
      </div>

    <% else %>

      <div class="col-md-2">
      </div>
      <div class="col-md-7">
        <%= link_to "首頁", todos_url, class: "pull-right"%>
      </div>
    <% end %>
   </div>


  <% end %>
</div>

<%#= onlyread %>

<br>
<br>
<br>

<% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

app/views/todos/edit.html.erb
<h1>編輯事項</h1>
<h1> </h1>
<h1> </h1>


<%#= render :partial => "form" ,  :read_only => false , :a => false %>

<%#= render :partial => "form" ,  locals: {zone: false} %>
<%#= render :partial => "form" ,  :zone => false} %>
<%#= render :partial => "form" ,  locals: {onlyread: false} %>
<%= render :partial => "form" ,  locals: {onlyread: false} %>

app/views/todos/index.html.erb
<div class="index_title">待辦事項</div>
<div id="new_item">
<%= link_to '新增待辦事項', new_todo_path, class: "btn btn-default btn-primary" %>
</div>
<h1> </h1>
<h1> </h1>
<% if true %> 
<table class="table table-striped">
   <thead>
    <tr>
      <th>確認</th>
      <th>項目</th>
      <th>內容</th>
      <th>編輯</th>
      <th>截止日</th>
      <th>刪除</th>
    </tr>
  </thead>
  <tbody>
    
  <% @todos.each do |todo|%>
    <tr>
      <td><%= check_box_tag :item_done, true, todo.done, data: { url: item_done_todo_path(todo), 
                method: :post, 
                remote: true }%></td>
      
      
      <td><%= todo.title %></td>
      <td><%= link_to "顯示", todo_path(todo)%></td>
      <td><%= link_to "編輯", edit_todo_path(todo) %></td>
      <td><%= todo.due_date.to_s.slice(0..9) %></td>

      <% if todo.due_date >= Date.today %>
        <td><%= link_to '刪除', todo_path(todo) ,method: :delete , data: {confirm:'are you sure?'}%></td>
      <% else %>
        <td> - </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>


<% end %>

app/views/todos/new.html.erb
<h1>新增事項</h1>
<h1> </h1>
<h1> </h1>
<%= render :partial => "form" ,  locals: {onlyread: false} %>

app/views/todos/show.html.erb
<h1>事項</h1>
<h1> </h1>
<h1> </h1>
<%= render :partial => "form" ,  locals: {onlyread: true} %>